[project]
name = "app1"
version = "0.1.0"
description = "Minimal FastAPI app for FusionAuth OAuth testing"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
    "jinja2>=3.1.0",
    "itsdangerous>=2.2.0",
]
